path: '/Users/petercripps/Code/datasets/'
csv-data: 'vodbull-data.csv'
col_names: ['Lname', 'Fname', 'Email', 'OptOut', 'TicketType', 'OrderDate', 'OrderRef', 'RepName', 'RepEmail', 'Confirm', 'DOB', 'Mobile', 'Uni']
debug: False