col_names:
- Lname
- Fname
- Email
- OptOut
- TicketType
- OrderDate
- OrderRef
- RepName
- RepEmail
- Uni
- Mobile
- DOB
- UniYear
csv-data: vodbull-data-ANON.csv
csv-edata: ''
csv-vdata: vodbull-vdata.csv
operation: analyse
path: /Users/petercripps/Code/datasets/
rules:
  DOB: true
  Email: true
  Mobile: true
  Uni: true
  UniYear: true
sort: UniYear
unilist:
- University of Birmingham
- UoB
- Aston
- BCU
- Loughborough University
- UCL
- Newman
- Coventry
- Nottingham Trent University
- Sheffield Hallam University
- Warwick University
uniyear:
- First
- Second
- Third
- Fourth
verbose: false
